### ISSUE TITLE
Update pelago/emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [dachcom-digital/pimcore-emailizr#2]
Emogrifier 2.0.0 has been released, fixing a lot of bugs. If the new PHP >= 5.5 requirement is not a problem, the dependency should be updated to ^2.0.0.

**Comment by ktallafus** [comment]
fixed with 9c23e884d8b4f7508c7f59cd78771c1dd74690e6

**Comment by oliverklee** [comment]
Thanks! ❤️
