### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by scrummer** [dachcom-digital/pimcore-emailizr#34]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Update `pelago/emogrifier` to `^4.0 | ^5.0 | ^6.0` as emogrifier starts PHP 8.1 support from v6.0.

According to their [changelog](https://github.com/MyIntervals/emogrifier/blob/main/CHANGELOG.md#600) this should not have any side effects.

**Comment by solverat** [comment]
I guess that's fine. Go ahead!
