### ISSUE TITLE
replace hampe/inky

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-emailizr#4]
https://github.com/thampe/inky is not longer maintained anymore.

**Comment by dpfaffenbauer** [comment]
replace with what?

**Comment by solverat** [comment]
There is [lorenzo/pinky](https://github.com/lorenzo/pinky) for example. Or we may just fork the abandoned repo. For now it's just a reminder, there are some other bundles out there with a dependency to hampe/inky so for now let's wait and see where they heading...
