### ISSUE TITLE
Twig 3.9.0 Support

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-emailizr#45]
| Q                | A      |
|------------------|--------|
| Bug report?      | yes |
| Feature request? | yes |
| BC Break report? | no |
| RFC?             | no |

Updating Twig from 3.8 to 3.9 breaks Emailizr: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty

**Comment by dpfaffenbauer** [comment]
FYI: https://github.com/pimcore/pimcore/pull/16976
